# Generated by Django 5.1 on 2024-08-23 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('league_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('league_name', models.CharField(max_length=100)),
                ('league_logo', models.ImageField(upload_to='leagues/')),
                ('league_country', models.CharField(max_length=100)),
                ('max_teams', models.PositiveIntegerField()),
                ('max_alloted_squad_size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('stat_id', models.AutoField(primary_key=True, serialize=False)),
                ('stat_of_player', models.CharField(default='player', max_length=100, unique=True)),
                ('goals', models.PositiveIntegerField(blank=True, default=0)),
                ('assists', models.PositiveIntegerField(blank=True, default=0)),
                ('clean_sheets', models.PositiveIntegerField(blank=True, default=0)),
                ('clearances', models.PositiveIntegerField(blank=True, default=0)),
                ('saves', models.PositiveIntegerField(blank=True, default=0)),
                ('performance', models.FloatField(blank=True, default=4.0)),
                ('matches_played', models.PositiveIntegerField(blank=True, default=0)),
                ('total_minutes_played', models.PositiveBigIntegerField(blank=True, default=0)),
                ('total_shots_taken', models.PositiveBigIntegerField(blank=True, default=0)),
                ('shots_on_target', models.PositiveBigIntegerField(blank=True, default=0)),
                ('passes', models.PositiveBigIntegerField(blank=True, default=0)),
                ('crosses', models.PositiveBigIntegerField(blank=True, default=0)),
                ('total_tackles', models.PositiveBigIntegerField(blank=True, default=0)),
                ('successful_tackles', models.PositiveBigIntegerField(blank=True, default=0)),
                ('successful_interceptions', models.PositiveBigIntegerField(blank=True, default=0)),
                ('total_shots_faced', models.PositiveBigIntegerField(blank=True, default=0)),
                ('fouls_made', models.PositiveIntegerField(blank=True, default=0)),
                ('yellow_cards', models.PositiveIntegerField(blank=True, default=0)),
                ('red_cards', models.PositiveIntegerField(blank=True, default=0)),
                ('offsides', models.PositiveIntegerField(blank=True, default=0)),
                ('penalties_taken', models.PositiveIntegerField(blank=True, default=0)),
                ('penalties_scored', models.PositiveIntegerField(blank=True, default=0)),
                ('freekicks_taken', models.PositiveIntegerField(blank=True, default=0)),
                ('freekicks_scored', models.PositiveIntegerField(blank=True, default=0)),
                ('headers_won', models.PositiveIntegerField(blank=True, default=0)),
                ('corners_taken', models.PositiveIntegerField(blank=True, default=0)),
                ('goals_conceded', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=100)),
                ('club_logo', models.ImageField(upload_to='clubs/')),
                ('club_country', models.CharField(max_length=200)),
                ('league_position', models.PositiveIntegerField()),
                ('squad_size', models.PositiveIntegerField()),
                ('primary_color', models.CharField(default='#ffffff', max_length=7)),
                ('secondary_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StatApp.league')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('player_first_name', models.CharField(blank=True, max_length=200)),
                ('player_last_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('country', models.CharField(max_length=70)),
                ('position', models.CharField(max_length=20)),
                ('ovr', models.PositiveIntegerField()),
                ('profile_image', models.ImageField(blank=True, upload_to='profiles/')),
                ('jersey_number', models.PositiveIntegerField(blank=True, default=999)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StatApp.club')),
                ('stat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StatApp.stat')),
            ],
        ),
    ]
