# Generated by Django 5.1 on 2024-08-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_logo',
            field=models.FileField(upload_to='clubs/'),
        ),
    ]
