# Generated by Django 5.1 on 2024-08-24 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StatApp', '0003_league_league_theme_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='league_theme_audio',
        ),
    ]
