# Generated by Django 5.1 on 2024-08-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StatApp', '0004_remove_league_league_theme_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='matches_played',
            new_name='appearances',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='total_minutes_played',
            new_name='total_minutes',
        ),
    ]
