# Generated by Django 5.1 on 2024-08-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatApp', '0005_rename_matches_played_stat_appearances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='blocks',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='own_goals',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='penalties_saved',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
