# Generated by Django 5.1 on 2024-08-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatApp', '0007_player_loaned_in_player_loaned_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='total_shots_faced',
            new_name='accurate_long_balls',
        ),
        migrations.AddField(
            model_name='stat',
            name='catches',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='goal_kicks',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='high_claims',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='motm_award',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='punches',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='throw_outs',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
