# Generated by Django 5.1 on 2024-08-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatApp', '0008_rename_total_shots_faced_stat_accurate_long_balls_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='motm_award',
            new_name='dribbles',
        ),
        migrations.AddField(
            model_name='stat',
            name='through_balls',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
