# Generated by Django 5.1 on 2024-08-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatApp', '0010_rename_dribbles_stat_successful_dribbles'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='current_champion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
