# Generated by Django 5.1 on 2024-08-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatApp', '0011_league_current_champion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='current_champion',
            new_name='current_champion_name',
        ),
        migrations.AddField(
            model_name='league',
            name='current_champion_logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
