# Generated by Django 5.1 on 2024-08-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatApp', '0013_rename_current_champion_name_league_current_champion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='performance',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
