# Generated by Django 5.1 on 2024-09-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatApp', '0014_alter_stat_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='popularity',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
