# Generated by Django 5.1 on 2024-09-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatApp', '0015_club_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='primary_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='league',
            name='text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
